### ISSUE TITLE
Assessing registration of HIFLD identified prisons in MS

### ISSUE THREAD

**Issue by shapironick** [Carceral-Ecologies/Carceral-ECHO-data#16]
In pursuit of better understanding the relationship between ECHO and HIFLD data re #1 we have been attempting to understand the following information in a **Mississippi** subset of the data. 

1. what percentage of OPEN prisons in HIFLD data are registered by the EPA in ECHO?

Our current answer for this subset just slightly less than **7%** 

2. are some prisons not registered but should be?  This also goes back to the question of when should a prison be listed in ECHO? 

I'm uploading the data here:
[Mississippi Carceral Data Nov 16 update.xlsx](https://github.com/Carceral-Ecologies/Carceral-ECHO-data/files/3855227/Mississippi.Carceral.Data.Nov.16.update.xlsx)

For more information about problems of prisons not being registered by EPA see this 2003 report: 
[EPA_2003_Prison_Initiative_article_original.pdf](https://github.com/Carceral-Ecologies/Carceral-ECHO-data/files/3855230/EPA_2003_Prison_Initiative_article_original.pdf)

Facilities that have high populations but are unregistered include:
USP   YAZOO CITY
FCI YAZOO CITY MEDIUM
FCI YAZOO CITY LOW
HINDS COUNTY RAYMOND DETENTION   CENTER
CI ADAMS COUNTY

We need to understand who much be registered to ECHO to answer # 2.

**Comment by benmillam** [comment]
I did some in depth searching for a handful of 'not found' prisons, and confirmed I couldn't find them in the EPA Facility Registry Service (FRS) data (although I did find a record that covers the [YAZOO prisons](https://ofmpub.epa.gov/frs_public2/fii_query_detail.disp_program_facility?p_registry_id=110003999969).

I searched the FRS data via Python and manually using the FRS web query tool: https://www.epa.gov/frs/frs-query casting very wide nets (e.g. returning all facilities in Raymond, MS, or all facilities in MS with 'FARM' in the street address) and then visually inspecting aided by Ctrl+F in Chrome. Sometimes I Googled facility names to confirm HIFLD data and found it useful (e.g. it appears YAZOO LOW/MEDIUM/HIGH prisons are all at the same location).

**Comment by shapironick** [comment]
Thank you, Ben! I've updated the spreadsheet based upon your excellent research. 
[Mississippi.Carceral.Data.Nov.19.update.xlsx](https://github.com/Carceral-Ecologies/Carceral-ECHO-data/files/3866938/Mississippi.Carceral.Data.Nov.19.update.xlsx)

I've now re-specified question 1 to be: Open (non-federal) facilities and now the answer is just over 7%.

Now that this data is double-checked. @nathanqtran922 will be working on the specifics of when a facility should be registered. And then our letter should be mail-ready. Thanks again, Ben!

**Comment by shapironick** [comment]
I found two more registered facilities as part of Parchman. 1 is their chicken egg business and the other looks like its what runs all the prison industrial labor. 

[Mississippi.Carceral.Data.Nov.20.update.xlsx](https://github.com/Carceral-Ecologies/Carceral-ECHO-data/files/3867527/Mississippi.Carceral.Data.Nov.20.update.xlsx)

**Comment by shapironick** [comment]
@nathanqtran922 has completed his (excellent) review of the inclusion criteria for inclusion in ECHO. its is posted here https://github.com/Carceral-Ecologies/Carceral-ECHO-data/blob/master/ECHO%20Inclusion%20Criteria.md 


Here is a slight update to the spreadsheet above: just includes some links that were left out:
[Mississippi.Carceral.Data.Nov.20.update.xlsx](https://github.com/Carceral-Ecologies/Carceral-ECHO-data/files/3889158/Mississippi.Carceral.Data.Nov.20.update.xlsx)

**Comment by shapironick** [comment]
I'll also say that Nathan's work indicates massive noncompliance, if there are not caveats to the law that we are not seeing.
