### ISSUE TITLE
Manual Coding--Raymond

### ISSUE THREAD

**Issue by NatRamya** [Carceral-Ecologies/Carceral-ECHO-data#26]
- [x] Manual Coding: Complete State 1 (Week 5)

Please enter what state you're coding for here once you get to this milestone.

- [ ] Manual Coding: Complete State 2 (Week 7)

Please enter what state you're coding for here once you get to this milestone.

- [ ] Manual Coding: Complete State 3 (Week 9)

Please enter what state you're coding for here once you get to this milestone.

- [ ] Manual Coding: Complete State 4 (Week 10)

Please enter what state you're coding for here once you get to this milestone.

Tasks to be added: Validating a state someone else coded

**Comment by koraymond53** [comment]
Completed the first round of manual coding for Oregon state.
