### ISSUE TITLE
Develop a dictionary of terms in the ECHO Dataset

### ISSUE THREAD

**Issue by lindsaypoirier** [Carceral-Ecologies/Carceral-ECHO-data#5]
It would be great to have a dictionary reference for the various terms in the ECHO dataset, including:
- facility
- violation
- enforcement
- penalty
- compliance
- inspection
- noncompliance
- significant noncompliance
- quarter
- others?

...with specific information about the scope of each of these terms in the context of ECHO, and how they relate to one another.

**Comment by shapironick** [comment]
To get further information that is not on the website email support@echo.zendesk.com
some of this may be covered already in issue #4 please see those responses (and associated links) before emailing echo

An additional question that was brought up last night was "How long does it take for a facility to be entered into the echo database after it is constructed?"  Thank you @nathanqtran922

**Comment by shapironick** [comment]
also there may be some helpful trainings here (ECHO website is down right now, so really just filing for future reading) https://echo.epa.gov/help/training#Series

**Comment by shapironick** [comment]
You can check them off as you go @nathanqtran922 :) Also when you find new terms to add in the other issue you can make check boxes for those two to help track your progress (its the check mark next to the horizontal lines icon above)

- [x] facility
- [x] violation
- [x] enforcement
- [x] penalty
- [x] compliance
- [x] inspection
- [x] noncompliance
- [x] significant noncompliance
- [x] quarter

**Comment by shapironick** [comment]
I'm also wondering what the Safe Drinking Water Act's Consumer Confidence Rule is and how it is broken. I'm seeing that as broken in some prisons
